name: otube
description: Alternative frontend for Youtube based on Invidious.
version: 1.0.0+1

environment:
  sdk: ">=2.9.0-14.0.dev.flutter-5c1376615e <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  video_player: ^0.10.11+1
  cached_network_image: ^2.2.0+1
  rxdart: ^0.24.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  bloc: ^4.0.0
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  chewie: ^0.9.10
  expandable: ^4.1.4
  intl: ^0.16.1
  get_it: ^4.0.2
  reflectable: ^2.2.4
  flutter_cache_store: ^0.7.2

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.8.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
